# Site settings
title: LeoChen008
url: "https://LeoChen008.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "" # the prefix of your site uri, eg. `"/jekyll-theme-EasyBook"` or empty string `""`
#timezone: Asia/ShangHai
description: >
  普通的记录博客
# Your information
email: leoandchen008@gmail.com
author: LeoChen008
avatar: "//www.gravatar.com/avatar/your_email_md5?d=mm&s=135"
profile: 这个人很懒，什么都不想说。
#twitter_username: twitter_username
#github_username:  github_username
profile_links:
  Email: "mailto:leoandchen008@gmail.com"
  GitHub: "https://github.com/LeoChen008"
  # You can add more profile links above, or edit _includes/sidebar.html 

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

excerpt_separator: <!==more==>

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    分类: /category/
    鸣谢: /about/
    #Donate: https://laobubu.net/donate.html

permalink: /:year/:month/:day/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
